### ISSUE TITLE
BlazeAINeoFPS error

### ISSUE THREAD

**Issue by marcusaggrippa** [TheWizardsCode/BlazeAINeoFPS#1]
Hi Sorra
I downloaded the repo(s) via git clone and followed the instructions to install NeoFPS and Blaze
I am left with one error

Assets\_BlazeNeo\Runtime\AI\NeoAI\EnemySpawner.cs(14,33): error CS0115: 'EnemySpawner.ShouldSpawn()': no suitable method found to override

keep up the good work it is much appreciated
Mark

**Comment by SorraTheOrc** [comment]
I'm sorry I missed this. I believe you brought this to Discord and we have got you past this point. If that's correct then I'll close this issue. If that is not correct and you are someone else then I have updated the README with the missing step (import the Character project - open source don't worry no cash needed)
